# Generated by Django 5.0.1 on 2024-01-09 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_users', '0003_alter_account_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={},
        ),
        migrations.RemoveField(
            model_name='account',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='user_permissions',
        ),
    ]
