# Generated by Django 5.0.1 on 2024-01-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_users', '0004_alter_account_options_remove_account_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
