# Generated by Django 5.0.1 on 2024-01-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('qty', models.FloatField(default=0.0)),
                ('cost', models.FloatField(default=0.0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(max_length=20)),
                ('shop_id', models.CharField(max_length=20)),
                ('remarks', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Stocks',
                'verbose_name_plural': 'Stocks',
            },
        ),
    ]
